# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sec1.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'sec1.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import constants_pb2 as constants__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nsec1.proto\x12\tespressif\x1a\x0f\x63onstants.proto\")\n\x0bSessionCmd1\x12\x1a\n\x12\x63lient_verify_data\x18\x02 \x01(\x0c\"M\n\x0cSessionResp1\x12!\n\x06status\x18\x01 \x01(\x0e\x32\x11.espressif.Status\x12\x1a\n\x12\x64\x65vice_verify_data\x18\x03 \x01(\x0c\"$\n\x0bSessionCmd0\x12\x15\n\rclient_pubkey\x18\x01 \x01(\x0c\"_\n\x0cSessionResp0\x12!\n\x06status\x18\x01 \x01(\x0e\x32\x11.espressif.Status\x12\x15\n\rdevice_pubkey\x18\x02 \x01(\x0c\x12\x15\n\rdevice_random\x18\x03 \x01(\x0c\"\xdb\x01\n\x0bSec1Payload\x12#\n\x03msg\x18\x01 \x01(\x0e\x32\x16.espressif.Sec1MsgType\x12%\n\x03sc0\x18\x14 \x01(\x0b\x32\x16.espressif.SessionCmd0H\x00\x12&\n\x03sr0\x18\x15 \x01(\x0b\x32\x17.espressif.SessionResp0H\x00\x12%\n\x03sc1\x18\x16 \x01(\x0b\x32\x16.espressif.SessionCmd1H\x00\x12&\n\x03sr1\x18\x17 \x01(\x0b\x32\x17.espressif.SessionResp1H\x00\x42\t\n\x07payload*g\n\x0bSec1MsgType\x12\x14\n\x10Session_Command0\x10\x00\x12\x15\n\x11Session_Response0\x10\x01\x12\x14\n\x10Session_Command1\x10\x02\x12\x15\n\x11Session_Response1\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sec1_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEC1MSGTYPE']._serialized_start=521
  _globals['_SEC1MSGTYPE']._serialized_end=624
  _globals['_SESSIONCMD1']._serialized_start=42
  _globals['_SESSIONCMD1']._serialized_end=83
  _globals['_SESSIONRESP1']._serialized_start=85
  _globals['_SESSIONRESP1']._serialized_end=162
  _globals['_SESSIONCMD0']._serialized_start=164
  _globals['_SESSIONCMD0']._serialized_end=200
  _globals['_SESSIONRESP0']._serialized_start=202
  _globals['_SESSIONRESP0']._serialized_end=297
  _globals['_SEC1PAYLOAD']._serialized_start=300
  _globals['_SEC1PAYLOAD']._serialized_end=519
# @@protoc_insertion_point(module_scope)
