# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: session.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'session.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import sec0_pb2 as sec0__pb2
from . import sec1_pb2 as sec1__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsession.proto\x12\tespressif\x1a\nsec0.proto\x1a\nsec1.proto\"\x94\x01\n\x0bSessionData\x12,\n\x07sec_ver\x18\x02 \x01(\x0e\x32\x1b.espressif.SecSchemeVersion\x12&\n\x04sec0\x18\n \x01(\x0b\x32\x16.espressif.Sec0PayloadH\x00\x12&\n\x04sec1\x18\x0b \x01(\x0b\x32\x16.espressif.Sec1PayloadH\x00\x42\x07\n\x05proto*2\n\x10SecSchemeVersion\x12\x0e\n\nSecScheme0\x10\x00\x12\x0e\n\nSecScheme1\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'session_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SECSCHEMEVERSION']._serialized_start=203
  _globals['_SECSCHEMEVERSION']._serialized_end=253
  _globals['_SESSIONDATA']._serialized_start=53
  _globals['_SESSIONDATA']._serialized_end=201
# @@protoc_insertion_point(module_scope)
