# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: wifi_config.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'wifi_config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import constants_pb2 as constants__pb2
from . import wifi_constants_pb2 as wifi__constants__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11wifi_config.proto\x12\tespressif\x1a\x0f\x63onstants.proto\x1a\x14wifi_constants.proto\"\x0e\n\x0c\x43mdGetStatus\"\xda\x01\n\rRespGetStatus\x12!\n\x06status\x18\x01 \x01(\x0e\x32\x11.espressif.Status\x12.\n\tsta_state\x18\x02 \x01(\x0e\x32\x1b.espressif.WifiStationState\x12\x39\n\x0b\x66\x61il_reason\x18\n \x01(\x0e\x32\".espressif.WifiConnectFailedReasonH\x00\x12\x32\n\tconnected\x18\x0b \x01(\x0b\x32\x1d.espressif.WifiConnectedStateH\x00\x42\x07\n\x05state\"P\n\x0c\x43mdSetConfig\x12\x0c\n\x04ssid\x18\x01 \x01(\x0c\x12\x12\n\npassphrase\x18\x02 \x01(\x0c\x12\r\n\x05\x62ssid\x18\x03 \x01(\x0c\x12\x0f\n\x07\x63hannel\x18\x04 \x01(\x05\"2\n\rRespSetConfig\x12!\n\x06status\x18\x01 \x01(\x0e\x32\x11.espressif.Status\"\x10\n\x0e\x43mdApplyConfig\"4\n\x0fRespApplyConfig\x12!\n\x06status\x18\x01 \x01(\x0e\x32\x11.espressif.Status\"\x89\x03\n\x11WiFiConfigPayload\x12)\n\x03msg\x18\x01 \x01(\x0e\x32\x1c.espressif.WiFiConfigMsgType\x12\x31\n\x0e\x63md_get_status\x18\n \x01(\x0b\x32\x17.espressif.CmdGetStatusH\x00\x12\x33\n\x0fresp_get_status\x18\x0b \x01(\x0b\x32\x18.espressif.RespGetStatusH\x00\x12\x31\n\x0e\x63md_set_config\x18\x0c \x01(\x0b\x32\x17.espressif.CmdSetConfigH\x00\x12\x33\n\x0fresp_set_config\x18\r \x01(\x0b\x32\x18.espressif.RespSetConfigH\x00\x12\x35\n\x10\x63md_apply_config\x18\x0e \x01(\x0b\x32\x19.espressif.CmdApplyConfigH\x00\x12\x37\n\x11resp_apply_config\x18\x0f \x01(\x0b\x32\x1a.espressif.RespApplyConfigH\x00\x42\t\n\x07payload*\x9e\x01\n\x11WiFiConfigMsgType\x12\x14\n\x10TypeCmdGetStatus\x10\x00\x12\x15\n\x11TypeRespGetStatus\x10\x01\x12\x14\n\x10TypeCmdSetConfig\x10\x02\x12\x15\n\x11TypeRespSetConfig\x10\x03\x12\x16\n\x12TypeCmdApplyConfig\x10\x04\x12\x17\n\x13TypeRespApplyConfig\x10\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wifi_config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WIFICONFIGMSGTYPE']._serialized_start=911
  _globals['_WIFICONFIGMSGTYPE']._serialized_end=1069
  _globals['_CMDGETSTATUS']._serialized_start=71
  _globals['_CMDGETSTATUS']._serialized_end=85
  _globals['_RESPGETSTATUS']._serialized_start=88
  _globals['_RESPGETSTATUS']._serialized_end=306
  _globals['_CMDSETCONFIG']._serialized_start=308
  _globals['_CMDSETCONFIG']._serialized_end=388
  _globals['_RESPSETCONFIG']._serialized_start=390
  _globals['_RESPSETCONFIG']._serialized_end=440
  _globals['_CMDAPPLYCONFIG']._serialized_start=442
  _globals['_CMDAPPLYCONFIG']._serialized_end=458
  _globals['_RESPAPPLYCONFIG']._serialized_start=460
  _globals['_RESPAPPLYCONFIG']._serialized_end=512
  _globals['_WIFICONFIGPAYLOAD']._serialized_start=515
  _globals['_WIFICONFIGPAYLOAD']._serialized_end=908
# @@protoc_insertion_point(module_scope)
