# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: wifi_scan.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'wifi_scan.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import constants_pb2 as constants__pb2
from . import wifi_constants_pb2 as wifi__constants__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fwifi_scan.proto\x12\tespressif\x1a\x0f\x63onstants.proto\x1a\x14wifi_constants.proto\"\\\n\x0c\x43mdScanStart\x12\x10\n\x08\x62locking\x18\x01 \x01(\x08\x12\x0f\n\x07passive\x18\x02 \x01(\x08\x12\x16\n\x0egroup_channels\x18\x03 \x01(\r\x12\x11\n\tperiod_ms\x18\x04 \x01(\r\"\x0f\n\rRespScanStart\"\x0f\n\rCmdScanStatus\"=\n\x0eRespScanStatus\x12\x15\n\rscan_finished\x18\x01 \x01(\x08\x12\x14\n\x0cresult_count\x18\x02 \x01(\r\"3\n\rCmdScanResult\x12\x13\n\x0bstart_index\x18\x01 \x01(\r\x12\r\n\x05\x63ount\x18\x02 \x01(\r\"s\n\x0eWiFiScanResult\x12\x0c\n\x04ssid\x18\x01 \x01(\x0c\x12\x0f\n\x07\x63hannel\x18\x02 \x01(\r\x12\x0c\n\x04rssi\x18\x03 \x01(\x05\x12\r\n\x05\x62ssid\x18\x04 \x01(\x0c\x12%\n\x04\x61uth\x18\x05 \x01(\x0e\x32\x17.espressif.WifiAuthMode\"<\n\x0eRespScanResult\x12*\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x19.espressif.WiFiScanResult\"\xa8\x03\n\x0fWiFiScanPayload\x12\'\n\x03msg\x18\x01 \x01(\x0e\x32\x1a.espressif.WiFiScanMsgType\x12!\n\x06status\x18\x02 \x01(\x0e\x32\x11.espressif.Status\x12\x31\n\x0e\x63md_scan_start\x18\n \x01(\x0b\x32\x17.espressif.CmdScanStartH\x00\x12\x33\n\x0fresp_scan_start\x18\x0b \x01(\x0b\x32\x18.espressif.RespScanStartH\x00\x12\x33\n\x0f\x63md_scan_status\x18\x0c \x01(\x0b\x32\x18.espressif.CmdScanStatusH\x00\x12\x35\n\x10resp_scan_status\x18\r \x01(\x0b\x32\x19.espressif.RespScanStatusH\x00\x12\x33\n\x0f\x63md_scan_result\x18\x0e \x01(\x0b\x32\x18.espressif.CmdScanResultH\x00\x12\x35\n\x10resp_scan_result\x18\x0f \x01(\x0b\x32\x19.espressif.RespScanResultH\x00\x42\t\n\x07payload*\x9c\x01\n\x0fWiFiScanMsgType\x12\x14\n\x10TypeCmdScanStart\x10\x00\x12\x15\n\x11TypeRespScanStart\x10\x01\x12\x15\n\x11TypeCmdScanStatus\x10\x02\x12\x16\n\x12TypeRespScanStatus\x10\x03\x12\x15\n\x11TypeCmdScanResult\x10\x04\x12\x16\n\x12TypeRespScanResult\x10\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wifi_scan_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WIFISCANMSGTYPE']._serialized_start=920
  _globals['_WIFISCANMSGTYPE']._serialized_end=1076
  _globals['_CMDSCANSTART']._serialized_start=69
  _globals['_CMDSCANSTART']._serialized_end=161
  _globals['_RESPSCANSTART']._serialized_start=163
  _globals['_RESPSCANSTART']._serialized_end=178
  _globals['_CMDSCANSTATUS']._serialized_start=180
  _globals['_CMDSCANSTATUS']._serialized_end=195
  _globals['_RESPSCANSTATUS']._serialized_start=197
  _globals['_RESPSCANSTATUS']._serialized_end=258
  _globals['_CMDSCANRESULT']._serialized_start=260
  _globals['_CMDSCANRESULT']._serialized_end=311
  _globals['_WIFISCANRESULT']._serialized_start=313
  _globals['_WIFISCANRESULT']._serialized_end=428
  _globals['_RESPSCANRESULT']._serialized_start=430
  _globals['_RESPSCANRESULT']._serialized_end=490
  _globals['_WIFISCANPAYLOAD']._serialized_start=493
  _globals['_WIFISCANPAYLOAD']._serialized_end=917
# @@protoc_insertion_point(module_scope)
